[workspace]
members = [
  "erc20-balances",
  "erc20-balances-rpc",
  "erc20-contracts",
  "erc20-contracts-rpc",
  "native-balances",
  "native-contracts",
  "uniswap-v2",
  "uniswap-v3",
  "proto",
  "common",
  "ens",
  "erc721",
  "erc721-rpc",
  "erc1155",
  "clickhouse",
  "clickhouse-nfts",
  # "clickhouse-ens",
]
resolver = "2"

[workspace.package]
description = "EVM Tokens"
edition = "2021"
version = "0.0.0"

[workspace.dependencies]
substreams = "0.6.1"
substreams-abis = "0.3.0"
substreams-ethereum = "0.10.4"

[profile.release]
lto = true
