[package]
name = "seaport"
description = { workspace = true }
edition = { workspace = true }
version = { workspace = true }
authors = ["Paulie <@PaulieB14>", "Denis <denis@pinax.network>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
substreams = { workspace = true }
substreams-ethereum = { workspace = true }
substreams-abis = { workspace = true }
tiny-keccak = { version = "2.0", features = ["default"] }

proto = { path = "../proto" }
common = { path = "../common" }
