[package]
name = "proto"
description = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
prost = "0.13"
prost-types = "0.13"